import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./_components/Footer";
import Notification from "./_components/Notification";
import Protected from "./protected/page";
import { ThemeProvider } from "next-themes";
import ThemeSwitch from "./_components/ThemeSwitch";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Pixel Infiniti Solutions",
  description: "Generated by create next app",
};

export const fetchCache = "force-no-store";
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section className="bg-[#f9fafb] dark:bg-gray-900">
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <section className="min-h-screen bg-[#f9fafb]  text-gray-950 relative dark:bg-gray-900 dark:text-gray-50 dark:text-opacity-90 transition-all duration-500">
              <Protected />
              <Notification />
              {children}
            </section>
            <Footer />
            <ThemeSwitch />
          </ThemeProvider>
        </section>
      </body>
    </html>
  );
}
